CC = gcc
CFLAGS = -Wall -g -O3
LDFLAGS = -lm -lc

all: mjpeg_encoder

mjpeg_encoder: mjpeg_encoder.o

clean:
	rm -f *.o mjpeg_encoder
	rm -f test.mjpeg

foreman: mjpeg_encoder
	./mjpeg_encoder -w 352 -h 288 -f 50 -o test.mjpeg foreman.yuv
